services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    user: "1000:1000"  # Map to typical first user UID/GID
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend   

  pgvector:
    image: pgvector/pgvector:0.8.0-pg17-trixie
    container_name: pgvector
    #user: "1000:1000"  # Map to typical first user UID/GID
    ports:
      - 5432:5432
    volumes:
      - pgvector_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongo-data:
  pgvector_data:
